name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies
        run: uv sync
      - name: Run Ruff Lint
        run: uv run ruff check --output-format=github .
      - name: Run Ruff Format
        run: uv run ruff format .
      - name: Run Tests
        run: uv run pytest tests/ -vv
